// import type { TvShow } from "./apiTypes";

// export const showCatalog: TvShow[] = [
//     {
//         id: 'backstage-lights',
//         title: 'Backstage Lights',
//         network: 'StreamHouse',
//         status: 'Airing',
//         episodesWatched: 6,
//         episodesTotal: 12,
//         nextEpisodeTitle: 'Half Time',
//         nextEpisode: 'S4E07',
//         nextReleaseDate: '2026-06-10',
//         description: 'A drama about an ensemble cast of performers balancing fame and family.',
//     },
//     {
//         id: 'kitchen-destiny',
//         title: 'Kitchen Destiny',
//         network: 'Foodly',
//         status: 'Airing',
//         episodesWatched: 10,
//         episodesTotal: 10,
//         nextEpisodeTitle: 'Final Course',
//         nextEpisode: 'S3E09',
//         nextReleaseDate: '2026-06-18',
//         description: 'Competition cooking series where each episode ends with a shocking twist.',
//     },
//     {
//         id: "tt32252772",
//         title: "Dexter: Original Sin",
//         network: "Dexter: Original Sin (2024) ",
//         status: "Released",
//         episodesWatched: 0,
//         episodesTotal: 1,
//         nextEpisodeTitle: "Year 2024",
//         nextEpisode: "2024",
//         nextReleaseDate: undefined,
//         description: "Patrick Gibson, Christian Slater",
//         posterUrl: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
//         seasons: [
//             {
//                 season: 1,
//                 episodes: [
//                     {
//                         id: "1-1",
//                         season: 1,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: true,
//                     },
//                     {
//                         id: "1-2",
//                         season: 1,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: true,
//                     },
//                     {
//                         id: "1-3",
//                         season: 1,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: true,
//                     },
//                     {
//                         id: "1-4",
//                         season: 1,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: true,
//                     },
//                     {
//                         id: "1-5",
//                         season: 1,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: true,
//                     },
//                     {
//                         id: "1-6",
//                         season: 1,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "1-7",
//                         season: 1,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "1-8",
//                         season: 1,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "1-9",
//                         season: 1,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "1-10",
//                         season: 1,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 2,
//                 episodes: [
//                     {
//                         id: "2-1",
//                         season: 2,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "2-2",
//                         season: 2,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "2-3",
//                         season: 2,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "2-4",
//                         season: 2,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "2-5",
//                         season: 2,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "2-6",
//                         season: 2,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "2-7",
//                         season: 2,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "2-8",
//                         season: 2,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "2-9",
//                         season: 2,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "2-10",
//                         season: 2,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 3,
//                 episodes: [
//                     {
//                         id: "3-1",
//                         season: 3,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "3-2",
//                         season: 3,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "3-3",
//                         season: 3,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "3-4",
//                         season: 3,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "3-5",
//                         season: 3,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "3-6",
//                         season: 3,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "3-7",
//                         season: 3,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "3-8",
//                         season: 3,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "3-9",
//                         season: 3,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "3-10",
//                         season: 3,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                     {
//                         id: "3-11",
//                         season: 3,
//                         episode: 11,
//                         title: "Episode 11",
//                         watched: false,
//                     },
//                 ],
//             },
//         ],
//     },
//     {
//         id: 'Ms. Marvel',
//         title: 'Ms. Marvel',
//         network: 'Disney+',
//         status: 'Airing',
//         episodesWatched: 6,
//         episodesTotal: 12,
//         nextEpisodeTitle: 'The Vault',
//         description: 'An adventure series following an international team of artifact thieves.',
//         posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzlkNjBmOWUtOTgzZS00OWIzLThkNWEtZTg5MGY2ODAyYzZjXkEyXkFqcGc@._V1_.jpg'
//     },
//     {
//         id: "tt0096697",
//         title: "The Simpsons",
//         network: "The Simpsons (1989) ",
//         status: "Released",
//         episodesWatched: 0,
//         episodesTotal: 1,
//         nextEpisodeTitle: "Year 1989",
//         nextEpisode: "1989",
//         nextReleaseDate: undefined,
//         description: "Dan Castellaneta, Nancy Cartwright",
//         posterUrl: "https://m.media-amazon.com/images/M/MV5BNTU2OWE0YWYtMjRlMS00NTUwLWJmZWUtODFhNzJiMGJlMzI3XkEyXkFqcGc@._V1_.jpg",
//         seasons: [
//             {
//                 season: 1,
//                 episodes: [
//                     {
//                         id: "1-1",
//                         season: 1,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: true,
//                     },
//                     {
//                         id: "1-2",
//                         season: 1,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: true,
//                     },
//                     {
//                         id: "1-3",
//                         season: 1,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: true,
//                     },
//                     {
//                         id: "1-4",
//                         season: 1,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: true,
//                     },
//                     {
//                         id: "1-5",
//                         season: 1,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: true,
//                     },
//                     {
//                         id: "1-6",
//                         season: 1,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "1-7",
//                         season: 1,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "1-8",
//                         season: 1,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "1-9",
//                         season: 1,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "1-10",
//                         season: 1,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 2,
//                 episodes: [
//                     {
//                         id: "2-1",
//                         season: 2,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "2-2",
//                         season: 2,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "2-3",
//                         season: 2,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "2-4",
//                         season: 2,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "2-5",
//                         season: 2,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "2-6",
//                         season: 2,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "2-7",
//                         season: 2,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "2-8",
//                         season: 2,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "2-9",
//                         season: 2,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "2-10",
//                         season: 2,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                     {
//                         id: "2-11",
//                         season: 2,
//                         episode: 11,
//                         title: "Episode 11",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 3,
//                 episodes: [
//                     {
//                         id: "3-1",
//                         season: 3,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "3-2",
//                         season: 3,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "3-3",
//                         season: 3,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "3-4",
//                         season: 3,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "3-5",
//                         season: 3,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "3-6",
//                         season: 3,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "3-7",
//                         season: 3,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "3-8",
//                         season: 3,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "3-9",
//                         season: 3,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "3-10",
//                         season: 3,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                     {
//                         id: "3-11",
//                         season: 3,
//                         episode: 11,
//                         title: "Episode 11",
//                         watched: false,
//                     },
//                 ],
//             },
//         ],
//     },
//     {
//         id: "tt8772296",
//         title: "Euphoria",
//         network: "Euphoria (2019) ",
//         status: "Released",
//         episodesWatched: 0,
//         episodesTotal: 1,
//         nextEpisodeTitle: "Year 2019",
//         nextEpisode: "2019",
//         nextReleaseDate: undefined,
//         description: "Zendaya, Hunter Schafer",
//         posterUrl: "https://m.media-amazon.com/images/M/MV5BYzg5MTVmNjgtMGQ3Zi00YThlLWFjMzgtYzc2NGUyMzE2MWQ1XkEyXkFqcGc@._V1_.jpg",
//         seasons: [
//             {
//                 season: 1,
//                 episodes: [
//                     {
//                         id: "1-1",
//                         season: 1,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: true,
//                     },
//                     {
//                         id: "1-2",
//                         season: 1,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: true,
//                     },
//                     {
//                         id: "1-3",
//                         season: 1,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: true,
//                     },
//                     {
//                         id: "1-4",
//                         season: 1,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: true,
//                     },
//                     {
//                         id: "1-5",
//                         season: 1,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: true,
//                     },
//                     {
//                         id: "1-6",
//                         season: 1,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "1-7",
//                         season: 1,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "1-8",
//                         season: 1,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "1-9",
//                         season: 1,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "1-10",
//                         season: 1,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                     {
//                         id: "1-11",
//                         season: 1,
//                         episode: 11,
//                         title: "Episode 11",
//                         watched: false,
//                     },
//                     {
//                         id: "1-12",
//                         season: 1,
//                         episode: 12,
//                         title: "Episode 12",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 2,
//                 episodes: [
//                     {
//                         id: "2-1",
//                         season: 2,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "2-2",
//                         season: 2,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "2-3",
//                         season: 2,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "2-4",
//                         season: 2,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "2-5",
//                         season: 2,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "2-6",
//                         season: 2,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "2-7",
//                         season: 2,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "2-8",
//                         season: 2,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "2-9",
//                         season: 2,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "2-10",
//                         season: 2,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                     {
//                         id: "2-11",
//                         season: 2,
//                         episode: 11,
//                         title: "Episode 11",
//                         watched: false,
//                     },
//                     {
//                         id: "2-12",
//                         season: 2,
//                         episode: 12,
//                         title: "Episode 12",
//                         watched: false,
//                     },
//                 ],
//             },
//             {
//                 season: 3,
//                 episodes: [
//                     {
//                         id: "3-1",
//                         season: 3,
//                         episode: 1,
//                         title: "Episode 1",
//                         watched: false,
//                     },
//                     {
//                         id: "3-2",
//                         season: 3,
//                         episode: 2,
//                         title: "Episode 2",
//                         watched: false,
//                     },
//                     {
//                         id: "3-3",
//                         season: 3,
//                         episode: 3,
//                         title: "Episode 3",
//                         watched: false,
//                     },
//                     {
//                         id: "3-4",
//                         season: 3,
//                         episode: 4,
//                         title: "Episode 4",
//                         watched: false,
//                     },
//                     {
//                         id: "3-5",
//                         season: 3,
//                         episode: 5,
//                         title: "Episode 5",
//                         watched: false,
//                     },
//                     {
//                         id: "3-6",
//                         season: 3,
//                         episode: 6,
//                         title: "Episode 6",
//                         watched: false,
//                     },
//                     {
//                         id: "3-7",
//                         season: 3,
//                         episode: 7,
//                         title: "Episode 7",
//                         watched: false,
//                     },
//                     {
//                         id: "3-8",
//                         season: 3,
//                         episode: 8,
//                         title: "Episode 8",
//                         watched: false,
//                     },
//                     {
//                         id: "3-9",
//                         season: 3,
//                         episode: 9,
//                         title: "Episode 9",
//                         watched: false,
//                     },
//                     {
//                         id: "3-10",
//                         season: 3,
//                         episode: 10,
//                         title: "Episode 10",
//                         watched: false,
//                     },
//                 ],
//             },
//         ],
//     }
// ];
