// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nextio.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615214500_NextReleaseDateAsDateTime")]
    partial class NextReleaseDateAsDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Data.UserMovie", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<string>("MovieId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PosterUrl").HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid>("UserId").HasColumnType("TEXT");
                    b.Property<DateTime>("WatchedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "MovieId").IsUnique();
                    b.ToTable("UserMovies");
                });

            modelBuilder.Entity("Data.UserTvShow", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<DateTime>("FollowedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsFollowing").HasColumnType("INTEGER");
                    b.Property<DateTime?>("LastSyncedAt").HasColumnType("TEXT");
                    b.Property<string>("Network").HasColumnType("TEXT");
                    b.Property<DateTime?>("NextReleaseDate").HasColumnType("TEXT");
                    b.Property<string>("PosterUrl").HasColumnType("TEXT");
                    b.Property<string>("ShowId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Status").HasColumnType("TEXT");
                    b.Property<string>("SyncError").HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("UserId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "ShowId").IsUnique();
                    b.ToTable("UserTvShows");
                });

            modelBuilder.Entity("Data.UserTvShowEpisode", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<int>("Episode").HasColumnType("INTEGER");
                    b.Property<int>("Season").HasColumnType("INTEGER");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<Guid>("UserTvShowId").HasColumnType("TEXT");
                    b.Property<bool>("Watched").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserTvShowId", "Season", "Episode").IsUnique();
                    b.ToTable("UserTvShowEpisodes");
                });

            modelBuilder.Entity("Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
                    b.Property<bool>("IsRevoked").HasColumnType("INTEGER");
                    b.Property<string>("ReplacedByToken").HasColumnType("TEXT");
                    b.Property<string>("Token").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid>("UserId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Token").IsUnique();
                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.UserTvShowEpisode", b =>
                {
                    b.HasOne("Data.UserTvShow", null)
                        .WithMany("Episodes")
                        .HasForeignKey("UserTvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.UserTvShow", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
